### ISSUE TITLE
Add support for VS2017

### ISSUE THREAD

**Issue by stickleprojects** [FireflyMigration/ClassOutline#5]

**Comment by HKleinsmit** [comment]
Hi Kieron,

I've tested the pre-release for VS 2017 of the Class Outline:

Bug: In VS 2017 (version 15.0.0+26228.9), when 2 programs were already open during startup, the Class Outline is only shown for the first one. When clicking on the second program the CO stays empty. The refresh buttons  in CO don't work either in this scenario.

Request: Could the 'Highlight UIcontroller' always set/default to ON? It now often looks like there are only 'batch' task within the program.

Best regards,
Harry Kleinsmit.

**Comment by stickleprojects** [comment]
HI
I cannot replicate the problem with 2 programs open, but it sounds like there's a bug when it scans the second program. Does this happen with specific programs or specific solution?

Highlight UI Controller - if you set it to ON using the tools/options/firefly menu, it stays on between sessions (the icon is a shortcut for "just this session of visual studio" rather than a permanent setting)

rgs
Kieron

**Comment by HKleinsmit** [comment]
Hi Kieron,

It happens for all projects with all programs. I will ask others if they have the same problem.

Thanks, that setting works.

Best regards,
Harry Kleinsmit.

Van: Kieron Wray [mailto:notifications@github.com]
Verzonden: zaterdag 18 maart 2017 08:17
Aan: FireflyMigration/ClassOutline
CC: Harry Kleinsmit; Comment
Onderwerp: Re: [FireflyMigration/ClassOutline] Add support for VS2017 (#5)


HI
I cannot replicate the problem with 2 programs open, but it sounds like there's a bug when it scans the second program. Does this happen with specific programs or specific solution?

Highlight UI Controller - if you set it to ON using the tools/options/firefly menu, it stays on between sessions (the icon is a shortcut for "just this session of visual studio" rather than a permanent setting)

rgs
Kieron

**Comment by HKleinsmit** [comment]
Hi Kieron,

Just upgraded to v1.9 of the ClassOutline and tested it on 3 different computers. All (still) have the same problem:

When I open a solution and then open 2 programs all is fine. CO works for both programs. Then I close VS and re-open it and open the same project again. The 2 programs are still (automatically) opened. It will show the CO only for the first program that is open. Not for the second one when I click on that tab. The 'Refresh' and 'Sync' buttons don't work in that case either. I've tested this with 2 different solutions and random programs.

If you need any more info that let me know at info@ka.nl

PS, perhaps it would be better to set the default to 'true' for the Highlight UI controller if you install it the first time as this complies with the way Magic shows this 'program tree'.

Best regards,
Harry Kleinsmit.

Van: Kieron Wray [mailto:notifications@github.com]
Verzonden: zaterdag 18 maart 2017 08:17
Aan: FireflyMigration/ClassOutline
CC: Harry Kleinsmit; Comment
Onderwerp: Re: [FireflyMigration/ClassOutline] Add support for VS2017 (#5)


HI
I cannot replicate the problem with 2 programs open, but it sounds like there's a bug when it scans the second program. Does this happen with specific programs or specific solution?

Highlight UI Controller - if you set it to ON using the tools/options/firefly menu, it stays on between sessions (the icon is a shortcut for "just this session of visual studio" rather than a permanent setting)

rgs
Kieron

**Comment by stickleprojects** [comment]
Hi
I wasnt aware of that feature. I'll look at this issue over the weekend and
revert.
Best

Leon

**Comment by stickleprojects** [comment]
fixed and now working in lightweight load mode
